### ISSUE TITLE
Quick code review

### ISSUE THREAD

**Issue by LewisJohnson** [Chubek/GuardianFlash#1]
Hey man, I've looked over your source and even poked at it in VS. Is this your first WPF app? Some of the variable names have way too much ambiguity, like ReadWindow.xaml and ReadReadWindow.xaml, this confused the hell out of me. 

So looking over the whole thing, it's a good start but some major refactoring needs to happen in the XAML's.

### ReadWindow.xaml

Holy moly this file. It works but isn't scalable or maintainable. The reason for this is that you just stuck everything into one grid, but you didn't use any grid properties. There are no grid row or column definitions, thus the sub components of the grid can not use the grid properties. I see you position everything with margins, which is an absolute NO! I used to do it when I started WPF but you'll quickly realise how bad it can be.

Secondly, I added some minimum and design dimensions. The minimum is quite self explanatory, you don't want users to scale the app smaller than the components can handle. The design dimension _d:DesignHeight_  is just so Visual Studio, and you, can test different scales quickly without touching the windows actual height and width dimensions.

I'll finish the review and fire up a new branch when I get home later. For the meantime, look over this ReadWindow.xaml I made up in a few minutes. The variable names have not been changed.

`
    <Window x:Class="GuardianFlash.ReadWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:GuardianFlash"
        mc:Ignorable="d"
        Title="ReadWindow" Height="Auto" Width="600" 
        MinHeight="460" MinWidth="400" 
        d:DesignHeight="460" d:DesignWidth="600">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <Grid Grid.Row="0">
            <TextBox x:Name="nameBox" HorizontalAlignment="Left" Height="23" Margin="52,10,0,0" TextWrapping="Wrap" VerticalAlignment="Top" Width="120"/>
            <Label x:Name="label" Content="Name" HorizontalAlignment="Left" Margin="10,10,0,0" VerticalAlignment="Top" RenderTransformOrigin="0.5,0.385"/>
            <Button x:Name="button" Content="Ok" HorizontalAlignment="Left" Margin="186,10,0,0" VerticalAlignment="Top" Width="75" Height="23" Click="button_Click"/>
        </Grid>

        <Grid Grid.Row="1">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>

            <Label Content="Front of card" Grid.Row="0" ></Label>
            <RichTextBox x:Name="frontTextBox" Grid.Row="1" Height="128" BorderThickness="1" Margin="5"/>

            <Label Content="Back of card" Grid.Row="2"></Label>
            <RichTextBox x:Name="backTextBox" Grid.Row="3" Height="128" BorderThickness="1" Margin="5"/>

            <Label Grid.Row="4" Content="Back of card"></Label>
            <ComboBox Grid.Row="4" x:Name="difficultyBox" HorizontalAlignment="Left" Width="120" SelectionChanged="difficultyBox_SelectionChanged">
                <ComboBoxItem Background="#FFF3E800" Content="Easy" IsSelected="True"/>
                <ComboBoxItem Background="#FFCCF770" Content="Medium"/>
                <ComboBoxItem Background="#FFF18A5A" Content="Hard"/>
                <ComboBoxItem Background="Red" Content="Very Hard"/>
            </ComboBox>
            <Button Grid.Row="5" x:Name="addButton" Content="Add" HorizontalAlignment="Left" Width="120" Height="45" Click="addButton_Click"/>
            <Button Grid.Row="5" x:Name="cancelButton" Content="Cancel" HorizontalAlignment="Right" Width="120" Height="45" Click="cancelButton_Click"/>
        </Grid>

    </Grid>
</Window>
`

**Comment by Chubek** [comment]
So grids... I didn't even know they exist. I added you as collaborator. Change what you want but tell me about them so I can learn. Thanks.
